import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  wrapper: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 0,
    marginBottom: 0,
  },
  symbolContainer: {
    width: "100%",
    height: 120,
    alignItems: "center",
    justifyContent: "center",
    overflow: "visible",
  },
  counterArea: {
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  digitsContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: -2,
    marginBottom: 6,
  },
  pulseGlowOuter: {
    position: "absolute",
    top: -32,
    left: -32,
    right: -32,
    bottom: -24,
    borderRadius: 44,
    backgroundColor: "rgba(155,81,224,0.28)",
    shadowColor: "#9B51E0",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
    elevation: 6,
  },
  pulseGlowInner: {
    position: "absolute",
    top: -16,
    left: -16,
    right: -16,
    bottom: -10,
    borderRadius: 28,
    backgroundColor: "rgba(155,81,224,0.5)",
    shadowColor: "#9B51E0",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 22,
    elevation: 10,
  },
  tooltipIcon: {
    position: "absolute",
    top: -15,
    right: -15,
  },
  tooltipBubble: {
    position: "absolute",
    top: -8,
    right: 20,
    maxWidth: 190,
    backgroundColor: "#123C69",
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    elevation: 6,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  tooltipText: {
    color: "#ffffff",
    fontSize: 13,
    lineHeight: 18,
  },
  daysLabel: {
    color: "#777777",
    fontSize: 21,
    fontWeight: "400",
    marginTop: -2,
  },
  dateForm: {
    width: "85%",
    marginTop: 15,
    alignItems: "center",
  },
  dateButton: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#cccccc",
    borderRadius: 10,
    padding: 10,
    backgroundColor: "#ffffff",
  },
  dateButtonText: {
    textAlign: "center",
    color: "#111111",
    fontSize: 16,
  },
  saveButton: {
    marginTop: 10,
    backgroundColor: "#111111",
    paddingVertical: 10,
    paddingHorizontal: 25,
    borderRadius: 10,
  },
  saveButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
  },
  tileText: {
    color: "#ffffff",
    fontSize: 25,
    fontWeight: "900",
    textShadowColor: "rgba(0,0,0,0.45)",
    textShadowOffset: {
      width: 0,
      height: 2,
    },
    textShadowRadius: 3,
  },
  confirmOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.45)",
    paddingHorizontal: 30,
  },
  confirmCard: {
    width: "100%",
    backgroundColor: "#ffffff",
    borderRadius: 14,
    padding: 20,
    elevation: 8,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
  },
  confirmTitle: {
    color: "#111111",
    fontSize: 17,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 20,
  },
  confirmButtonRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 12,
  },
  confirmNoButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: "#e5e5e5",
    alignItems: "center",
  },
  confirmNoButtonText: {
    color: "#111111",
    fontSize: 16,
    fontWeight: "600",
  },
  confirmYesButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: "#cc3333",
    alignItems: "center",
  },
  confirmYesButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
  },
});