export type Difficulty = "Easy" | "Moderate" | "Challenge";

export type Suggestion = {
  difficulty: Difficulty;
  idea: string;
  why: string;
};

const suggestions: Suggestion[] = [
  // ========== EASY ==========
  { difficulty: "Easy", idea: "Make yourself a hot drink.", why: "A small comfort can settle your body and give you a gentle pause." },
  { difficulty: "Easy", idea: "Drink a full glass of water.", why: "Simple and useful. Your body often needs this more than you notice." },
  { difficulty: "Easy", idea: "Open a window for five minutes.", why: "Fresh air and a change of atmosphere can quietly shift how you feel." },
  { difficulty: "Easy", idea: "Step outside and take ten slow breaths.", why: "Getting outside and slowing your breathing helps reset your system." },
  { difficulty: "Easy", idea: "Walk to the end of the street and back.", why: "A short walk gives movement without asking too much of you." },
  { difficulty: "Easy", idea: "Walk around the block.", why: "A bit more movement and a change of scene can clear your head." },
  { difficulty: "Easy", idea: "Put away five things that are out of place.", why: "A small tidy-up can make the space around you feel calmer." },
  { difficulty: "Easy", idea: "Wipe down the kitchen counter.", why: "One clean surface can make the whole room feel better." },
  { difficulty: "Easy", idea: "Sweep one small area of the floor.", why: "A short practical task gives you a clear finish point." },
  { difficulty: "Easy", idea: "Wash a few dishes.", why: "A simple job with a clear result. Useful and grounding." },
  { difficulty: "Easy", idea: "Empty the kitchen bin.", why: "A small act of care for your living space." },
  { difficulty: "Easy", idea: "Change the bin bag.", why: "Keeps things clean and gives you a quick sense of order." },
  { difficulty: "Easy", idea: "Make your bed.", why: "Starting with the bed can make the whole day feel more settled." },
  { difficulty: "Easy", idea: "Straighten the pillows and blankets.", why: "A tiny improvement that makes the space feel cared for." },
  { difficulty: "Easy", idea: "Put dirty clothes into the laundry basket.", why: "Removes clutter and takes one small job off your mind." },
  { difficulty: "Easy", idea: "Fold five pieces of clothing.", why: "A short, manageable task with a clear end." },
  { difficulty: "Easy", idea: "Put one load of washing on.", why: "A practical step that helps the day feel more organised." },
  { difficulty: "Easy", idea: "Hang up a few clothes.", why: "Keeps things from piling up and creates a little order." },
  { difficulty: "Easy", idea: "Clean the bathroom sink.", why: "One clean surface can improve how the whole room feels." },
  { difficulty: "Easy", idea: "Wipe the bathroom mirror.", why: "A quick clean that makes the space feel fresher." },
  { difficulty: "Easy", idea: "Replace the toilet roll.", why: "A small act of care that is easy to overlook." },
  { difficulty: "Easy", idea: "Put fresh towels in the bathroom.", why: "A simple way to make the space feel looked after." },
  { difficulty: "Easy", idea: "Water the plants.", why: "Looking after something living can feel quietly grounding." },
  { difficulty: "Easy", idea: "Remove dead leaves from a plant.", why: "A small bit of care that improves what you see around you." },
  { difficulty: "Easy", idea: "Feed a pet.", why: "A simple responsibility that can feel steadying." },
  { difficulty: "Easy", idea: "Brush or play with a pet.", why: "Gentle contact and routine can help settle your mood." },
  { difficulty: "Easy", idea: "Stand outside and notice five things you can see.", why: "It pulls your attention into the present without pressure." },
  { difficulty: "Easy", idea: "Stretch your arms, shoulders and legs.", why: "Light movement can release tension you may not have noticed." },
  { difficulty: "Easy", idea: "Walk up and down the stairs a few times.", why: "Short bursts of movement can shift restless energy." },
  { difficulty: "Easy", idea: "Put on one song and move around while it plays.", why: "Music and movement together can change how your body feels." },
  { difficulty: "Easy", idea: "Sit somewhere quiet without your phone for five minutes.", why: "A short break from screens can lower the noise in your head." },
  { difficulty: "Easy", idea: "Wash your face.", why: "A simple reset that often helps more than expected." },
  { difficulty: "Easy", idea: "Brush your teeth.", why: "Basic self-care that supports dignity and routine." },
  { difficulty: "Easy", idea: "Take a quick shower.", why: "Washing can help you feel more present and steady." },
  { difficulty: "Easy", idea: "Change into clean, comfortable clothes.", why: "Feeling clean and comfortable can quietly improve your mood." },
  { difficulty: "Easy", idea: "Comb or brush your hair.", why: "A small act of looking after yourself." },
  { difficulty: "Easy", idea: "Put moisturiser on your hands or face.", why: "A gentle, practical way of caring for your body." },
  { difficulty: "Easy", idea: "Prepare a simple snack.", why: "Feeding yourself is a basic and important form of care." },
  { difficulty: "Easy", idea: "Eat a piece of fruit.", why: "A small healthy choice that is easy to do right now." },
  { difficulty: "Easy", idea: "Clear one small surface.", why: "One clear space can make the room feel less heavy." },
  { difficulty: "Easy", idea: "Sort one drawer for five minutes.", why: "A short, contained task with a visible result." },
  { difficulty: "Easy", idea: "Throw away five pieces of rubbish.", why: "Removes clutter and gives a quick sense of progress." },
  { difficulty: "Easy", idea: "Delete ten unwanted photos from your phone.", why: "A small digital tidy that reduces mental noise." },
  { difficulty: "Easy", idea: "Reply to one message you have been putting off.", why: "Clearing one small communication can lift a quiet weight." },
  { difficulty: "Easy", idea: "Write down three things you need to do today.", why: "Getting things out of your head makes them easier to handle." },
  { difficulty: "Easy", idea: "Write down one thing you have already managed today.", why: "Noticing what you have done helps against the feeling of failure." },
  { difficulty: "Easy", idea: "Read two pages of a book.", why: "A short break that gives your mind something steady to follow." },
  { difficulty: "Easy", idea: "Sit by the window and watch what is happening outside.", why: "Soft attention on the outside world can quieten internal noise." },
  { difficulty: "Easy", idea: "Put something ready for tomorrow.", why: "A small act of preparation that makes the next day easier." },
  { difficulty: "Easy", idea: "Choose one small job and finish it completely.", why: "Finishing something, even small, builds a sense of capability." },

  // ========== MODERATE ==========
  { difficulty: "Moderate", idea: "Take a 15–20 minute walk.", why: "Longer movement helps discharge stress and clear your head." },
  { difficulty: "Moderate", idea: "Walk to a nearby park or quiet public place.", why: "A change of environment can shift your mental state." },
  { difficulty: "Moderate", idea: "Visit a library and browse for a while.", why: "A calm public space with no pressure to spend money or talk." },
  { difficulty: "Moderate", idea: "Read a chapter of a book.", why: "Gives your mind a longer stretch of steady focus." },
  { difficulty: "Moderate", idea: "Listen to a full podcast episode.", why: "Useful company and distraction without needing to socialise." },
  { difficulty: "Moderate", idea: "Listen to an album or a few favourite songs.", why: "Music can regulate mood and fill time in a healthy way." },
  { difficulty: "Moderate", idea: "Do a 15-minute stretching routine.", why: "Releases physical tension and helps you feel more in your body." },
  { difficulty: "Moderate", idea: "Follow a short beginner exercise video.", why: "Structured movement when you need a bit more than a walk." },
  { difficulty: "Moderate", idea: "Walk up and down a safe set of steps for ten minutes.", why: "Builds a bit of energy and focus through simple repetition." },
  { difficulty: "Moderate", idea: "Sit somewhere peaceful and practise slow breathing.", why: "A deliberate pause that helps settle anxiety or restlessness." },
  { difficulty: "Moderate", idea: "Write a short journal entry.", why: "Gets thoughts out of your head and onto paper." },
  { difficulty: "Moderate", idea: "Write down three things that are going well.", why: "Balances the mind when it is stuck on what is wrong." },
  { difficulty: "Moderate", idea: "Write down three things you want to improve.", why: "Turns vague dissatisfaction into something clearer and more useful." },
  { difficulty: "Moderate", idea: "Make a simple plan for the rest of the day.", why: "Structure reduces the feeling of drifting or being overwhelmed." },
  { difficulty: "Moderate", idea: "Make a list of important phone numbers.", why: "Practical preparation that can help in difficult moments." },
  { difficulty: "Moderate", idea: "Call someone you trust.", why: "Real connection is often more helpful than staying alone with thoughts." },
  { difficulty: "Moderate", idea: "Send a message to someone you have lost touch with.", why: "A low-pressure way to rebuild a supportive connection." },
  { difficulty: "Moderate", idea: "Check in with another person in recovery.", why: "Shared experience can reduce isolation and shame." },
  { difficulty: "Moderate", idea: "Attend an in-person recovery meeting.", why: "Being in the room with others can strengthen your recovery." },
  { difficulty: "Moderate", idea: "Join an online recovery meeting.", why: "Support is available even when leaving the house feels hard." },
  { difficulty: "Moderate", idea: "Look up the times of nearby support meetings.", why: "Knowing your options makes it easier to go when you need to." },
  { difficulty: "Moderate", idea: "Visit a community or day centre.", why: "A safe place with structure and people when you need somewhere to go." },
  { difficulty: "Moderate", idea: "Ask a support service what activities are available.", why: "Opens doors you may not have known about." },
  { difficulty: "Moderate", idea: "Spend time in a church, community centre or other quiet public space.", why: "A calm place to be without having to explain yourself." },
  { difficulty: "Moderate", idea: "Go to a free museum, gallery or local exhibition.", why: "Gives your mind something interesting and different to focus on." },
  { difficulty: "Moderate", idea: "Walk around a shopping centre without buying anything.", why: "Movement and people-watching without spending money." },
  { difficulty: "Moderate", idea: "Explore a street or area you have not walked through before.", why: "Novelty can break repetitive or stuck thinking." },
  { difficulty: "Moderate", idea: "Sit in a public place and notice what is happening around you.", why: "Softens self-focus and brings you into the present." },
  { difficulty: "Moderate", idea: "Take photographs of five interesting things.", why: "Encourages you to look outward and notice detail." },
  { difficulty: "Moderate", idea: "Draw or sketch something you can see.", why: "A quiet, focused activity that does not need to be good." },
  { difficulty: "Moderate", idea: "Write a short poem, story or song.", why: "Gives difficult feelings a creative place to go." },
  { difficulty: "Moderate", idea: "Complete a crossword, word search or puzzle.", why: "Occupies the mind in a structured, low-pressure way." },
  { difficulty: "Moderate", idea: "Play a free game on your phone.", why: "A short, contained distraction when you need a break." },
  { difficulty: "Moderate", idea: "Delete unwanted photos or files from your phone.", why: "Reduces digital clutter and the quiet stress that comes with it." },
  { difficulty: "Moderate", idea: "Organise your phone contacts.", why: "A practical tidy that can also surface supportive numbers." },
  { difficulty: "Moderate", idea: "Clear old messages or emails for 15 minutes.", why: "Removes a background source of pressure." },
  { difficulty: "Moderate", idea: "Research one free local activity.", why: "Expands your options for healthy ways to spend time." },
  { difficulty: "Moderate", idea: "Look up one course, class or training opportunity.", why: "A step toward structure, skill or purpose." },
  { difficulty: "Moderate", idea: "Update part of your CV.", why: "A practical investment in your future self." },
  { difficulty: "Moderate", idea: "Write down your recent achievements.", why: "Counters the tendency to only see what is still wrong." },
  { difficulty: "Moderate", idea: "Practise something useful, such as spelling, maths or typing.", why: "Builds competence in small, concrete ways." },
  { difficulty: "Moderate", idea: "Learn a few words in another language.", why: "A light mental stretch that is interesting and contained." },
  { difficulty: "Moderate", idea: "Watch a short educational video.", why: "Feeds curiosity without demanding too much energy." },
  { difficulty: "Moderate", idea: "Help someone with a small task.", why: "Being useful to someone else can lift your own mood." },
  { difficulty: "Moderate", idea: "Pick up litter in a safe public area.", why: "A small contribution to the place around you." },
  { difficulty: "Moderate", idea: "Return something you borrowed.", why: "Clears a quiet obligation and builds self-respect." },
  { difficulty: "Moderate", idea: "Wash a few clothes by hand, where facilities are available.", why: "Practical self-care when other options are limited." },
  { difficulty: "Moderate", idea: "Organise the belongings you currently have with you.", why: "Creates order and reduces the feeling of chaos." },
  { difficulty: "Moderate", idea: "Prepare yourself for tomorrow by checking appointments and travel plans.", why: "Reduces next-day stress by dealing with it now." },
  { difficulty: "Moderate", idea: "Choose one task you have been avoiding and work on it for 20 minutes.", why: "Starting is often harder than continuing. Twenty minutes is enough to begin." },

  // ========== CHALLENGE ==========
  { difficulty: "Challenge", idea: "Call a friend you have not spoken to in a long time.", why: "Rebuilding connection takes courage and often helps more than expected." },
  { difficulty: "Challenge", idea: "Tell someone you trust that you are having a difficult day.", why: "Letting someone in reduces the weight of carrying it alone." },
  { difficulty: "Challenge", idea: "Ask someone for help instead of trying to manage alone.", why: "Asking for help is a strength, not a failure." },
  { difficulty: "Challenge", idea: "Attend a recovery meeting you have never been to before.", why: "New rooms can offer new perspectives and connections." },
  { difficulty: "Challenge", idea: "Speak during a recovery meeting.", why: "Sharing can reduce isolation and strengthen your own recovery." },
  { difficulty: "Challenge", idea: "Introduce yourself to someone new at a meeting.", why: "Connection is often built one small introduction at a time." },
  { difficulty: "Challenge", idea: "Call your sponsor, key worker or support person.", why: "Using your support network is a core recovery skill." },
  { difficulty: "Challenge", idea: "Ask someone to meet you for a coffee or a walk.", why: "Reaching out for company is healthier than isolating." },
  { difficulty: "Challenge", idea: "Reconnect with a supportive family member.", why: "Where it is safe, family connection can be a strong resource." },
  { difficulty: "Challenge", idea: "Apologise to someone you have hurt, where it is safe and appropriate.", why: "Making amends can reduce shame and repair important relationships." },
  { difficulty: "Challenge", idea: "Accept an apology without reopening the argument.", why: "Letting something finish is often harder than continuing it." },
  { difficulty: "Challenge", idea: "Set a clear boundary with someone.", why: "Boundaries protect your recovery and your peace." },
  { difficulty: "Challenge", idea: "Say no to something that could put your recovery at risk.", why: "Protecting your recovery is more important than pleasing others." },
  { difficulty: "Challenge", idea: "Distance yourself from someone who encourages harmful behaviour.", why: "Your environment strongly influences your chances of staying well." },
  { difficulty: "Challenge", idea: "Delete a dealer's or drinking contact's number.", why: "Removing easy access reduces the chance of acting on a craving." },
  { difficulty: "Challenge", idea: "Avoid a place strongly connected with drinking or drug use.", why: "Changing your environment is one of the most practical recovery tools." },
  { difficulty: "Challenge", idea: "Tell someone honestly about a craving.", why: "Speaking a craving out loud often weakens its hold." },
  { difficulty: "Challenge", idea: "Write down what could happen if you relapsed.", why: "Clear consequences can strengthen your resolve when feelings are strong." },
  { difficulty: "Challenge", idea: "Write a plan for getting through your next strong craving.", why: "Having a plan ready makes it easier to act when you need it." },
  { difficulty: "Challenge", idea: "Make a list of your main triggers.", why: "Knowing your triggers helps you prepare for them." },
  { difficulty: "Challenge", idea: "Make a list of people you can contact in an emergency.", why: "A ready list removes hesitation when you need support quickly." },
  { difficulty: "Challenge", idea: "Write honestly about the hardest part of your recovery.", why: "Naming the hard parts makes them less powerful in the dark." },
  { difficulty: "Challenge", idea: "Write a letter to your past self.", why: "Can bring compassion and perspective to where you have been." },
  { difficulty: "Challenge", idea: "Write a letter to the person you want to become.", why: "Helps you stay connected to the future you are working toward." },
  { difficulty: "Challenge", idea: "Write down five things recovery has already given you.", why: "Reminds you what is at stake and what you have already gained." },
  { difficulty: "Challenge", idea: "Spend one full hour without social media.", why: "Creates space from comparison, noise and easy distraction." },
  { difficulty: "Challenge", idea: "Spend an evening away from people who make recovery harder.", why: "Protecting your environment is part of protecting yourself." },
  { difficulty: "Challenge", idea: "Go for a 30–45 minute walk.", why: "Longer movement can significantly shift mood and craving intensity." },
  { difficulty: "Challenge", idea: "Complete a challenging workout suitable for your fitness level.", why: "Physical effort can discharge difficult feelings in a healthy way." },
  { difficulty: "Challenge", idea: "Attend a free class, group or community activity alone.", why: "Builds confidence and expands your world beyond recovery rooms." },
  { difficulty: "Challenge", idea: "Visit a library or community centre and ask what services are available.", why: "Finding real-world resources strengthens your support system." },
  { difficulty: "Challenge", idea: "Ask a support organisation about housing, treatment or welfare help.", why: "Practical support can remove major sources of stress and risk." },
  { difficulty: "Challenge", idea: "Make a medical, counselling or support appointment you have been avoiding.", why: "Facing avoided appointments removes a background source of anxiety." },
  { difficulty: "Challenge", idea: "Attend an appointment you are nervous about.", why: "Showing up is often the hardest and most important part." },
  { difficulty: "Challenge", idea: "Complete an important form or application.", why: "Administrative tasks often block progress until they are faced." },
  { difficulty: "Challenge", idea: "Deal with one overdue bill, letter or official message.", why: "Facing one avoided thing reduces the pile and the fear around it." },
  { difficulty: "Challenge", idea: "Update your CV.", why: "A concrete step toward work, training or a more stable future." },
  { difficulty: "Challenge", idea: "Apply for one job, course or volunteering opportunity.", why: "Action toward purpose and structure is a strong recovery support." },
  { difficulty: "Challenge", idea: "Ask someone to help you practise for an interview.", why: "Using support makes difficult steps more manageable." },
  { difficulty: "Challenge", idea: "Volunteer to help at a meeting or community organisation.", why: "Being useful to others strengthens your own recovery." },
  { difficulty: "Challenge", idea: "Offer support to someone else without trying to fix everything for them.", why: "Healthy helping builds connection without over-responsibility." },
  { difficulty: "Challenge", idea: "Clean and organise all the belongings you currently have with you.", why: "External order can support internal calm." },
  { difficulty: "Challenge", idea: "Get rid of something that reminds you strongly of your old lifestyle.", why: "Removing triggers from your environment protects your recovery." },
  { difficulty: "Challenge", idea: "Plan the next seven days in advance.", why: "Structure reduces the chance of empty time turning into risk." },
  { difficulty: "Challenge", idea: "Plan how you will handle an upcoming risky event or social occasion.", why: "Preparation is one of the best defences against relapse." },
  { difficulty: "Challenge", idea: "Spend a full day without contacting anyone connected to your past use.", why: "Creates clear space from old patterns and influences." },
  { difficulty: "Challenge", idea: "Try a new healthy activity that makes you uncomfortable or nervous.", why: "Growth in recovery often sits just outside your comfort zone." },
  { difficulty: "Challenge", idea: "Finish a difficult task you have been avoiding.", why: "Completing avoided tasks builds self-trust." },
  { difficulty: "Challenge", idea: "Ask yourself what is currently threatening your recovery and take one real step to deal with it.", why: "Honest self-appraisal followed by action is at the heart of staying well." },
];

export default suggestions;
