import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  background: {
    flex: 1,
  },
  scrollContent: {
    padding: 24,
    paddingTop: 50,
    paddingBottom: 90,
  },
  title: {
    color: "#123C69",
    fontSize: 34,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 8,
  },
  subtitle: {
    color: "#263238",
    fontSize: 18,
    textAlign: "center",
    lineHeight: 26,
    marginBottom: 24,
    fontWeight: "600",
  },
  card: {
    backgroundColor: "rgba(255,255,255,0.9)",
    borderRadius: 26,
    padding: 18,
    borderWidth: 2,
    marginBottom: 20,
    elevation: 6,
  },
  storiesCard: {
    borderColor: "#2E7D6B",
  },
  themesCard: {
    borderColor: "#9B51E0",
  },
  shareCard: {
    borderColor: "#F2994A",
  },
  cardTitle: {
    color: "#123C69",
    fontSize: 24,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 10,
  },
  cardText: {
    color: "#263238",
    fontSize: 16,
    lineHeight: 24,
    textAlign: "center",
    marginBottom: 16,
    fontWeight: "600",
  },
  primaryButton: {
    borderRadius: 22,
    paddingVertical: 15,
    alignItems: "center",
    borderBottomWidth: 4,
  },
  readStoriesButton: {
    backgroundColor: "#2E7D6B",
    borderBottomColor: "#1F5A4C",
  },
  submitStoryButton: {
    backgroundColor: "#F2994A",
    borderBottomColor: "#C76E27",
  },
  primaryButtonText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "900",
  },
  themesTitle: {
    color: "#123C69",
    fontSize: 24,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 14,
  },
  themesRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  themeButton: {
    width: "48%",
    backgroundColor: "#ffffff",
    borderWidth: 2,
    borderColor: "#9B51E0",
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 8,
    alignItems: "center",
    marginBottom: 12,
    borderBottomWidth: 4,
    borderBottomColor: "#D7B5F4",
  },
  themeButtonText: {
    color: "#123C69",
    fontSize: 15,
    fontWeight: "900",
    textAlign: "center",
  },
  profilePicButton: {
    backgroundColor: "#ffffff",
    borderWidth: 2,
    borderColor: "#F2994A",
    borderRadius: 22,
    paddingVertical: 15,
    alignItems: "center",
    marginBottom: 14,
    borderBottomWidth: 4,
    borderBottomColor: "#FFD1A0",
  },
  profilePicButtonText: {
    color: "#123C69",
    fontSize: 17,
    fontWeight: "900",
  },
  noteCard: {
    backgroundColor: "rgba(255,255,255,0.82)",
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(18,60,105,0.25)",
  },
  noteTitle: {
    color: "#123C69",
    fontSize: 20,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 10,
  },
  noteText: {
    color: "#263238",
    fontSize: 15,
    lineHeight: 23,
    textAlign: "center",
  },
});
