import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  background: {
    flex: 1,
  },
  scrollContent: {
    padding: 24,
    paddingTop: 50,
    paddingBottom: 90,
  },
  title: {
    color: "#123C69",
    fontSize: 34,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 8,
  },
  subtitle: {
    color: "#263238",
    fontSize: 18,
    textAlign: "center",
    lineHeight: 26,
    marginBottom: 24,
    fontWeight: "600",
  },
  formCard: {
    backgroundColor: "rgba(255,255,255,0.9)",
    borderRadius: 26,
    padding: 18,
    borderWidth: 2,
    borderColor: "#2E7D6B",
    marginBottom: 20,
    elevation: 6,
  },
  formTitle: {
    color: "#123C69",
    fontSize: 23,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 14,
  },
  input: {
    backgroundColor: "#ffffff",
    borderWidth: 2,
    borderColor: "#2E7D6B",
    borderRadius: 18,
    padding: 14,
    color: "#111111",
    fontSize: 17,
    marginBottom: 12,
  },
  timeInput: {
    marginBottom: 8,
  },
  helperText: {
    color: "#263238",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 16,
    textAlign: "center",
    fontWeight: "700",
  },
  fieldLabel: {
    color: "#123C69",
    fontSize: 17,
    fontWeight: "900",
    marginBottom: 10,
    textAlign: "center",
  },
  remindOptionsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  messageHelperText: {
    color: "#263238",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 14,
    textAlign: "center",
    fontWeight: "700",
  },
  messageOptionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  previewBox: {
    backgroundColor: "rgba(18,60,105,0.08)",
    borderRadius: 18,
    padding: 14,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: "rgba(18,60,105,0.25)",
  },
  previewLabel: {
    color: "#123C69",
    fontSize: 16,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 4,
  },
  previewAppName: {
    color: "#123C69",
    fontSize: 18,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 2,
  },
  previewMessage: {
    color: "#263238",
    fontSize: 16,
    fontWeight: "700",
    textAlign: "center",
  },
  alarmPreviewBox: {
    backgroundColor: "rgba(46,125,107,0.12)",
    borderRadius: 18,
    padding: 14,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: "rgba(46,125,107,0.35)",
  },
  alarmPreviewTitle: {
    color: "#123C69",
    fontSize: 16,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 4,
  },
  alarmPreviewDetails: {
    color: "#263238",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
  },
  saveButton: {
    backgroundColor: "#2E7D6B",
    borderRadius: 22,
    paddingVertical: 15,
    alignItems: "center",
    borderBottomWidth: 4,
    borderBottomColor: "#1F5A4C",
    elevation: 5,
  },
  saveButtonText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "900",
  },
  savedRemindersTitle: {
    color: "#123C69",
    fontSize: 24,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 14,
  },
  noteCard: {
    backgroundColor: "rgba(255,255,255,0.82)",
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(18,60,105,0.25)",
    marginTop: 8,
  },
  noteTitle: {
    color: "#123C69",
    fontSize: 20,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 10,
  },
  noteText: {
    color: "#263238",
    fontSize: 15,
    lineHeight: 23,
    textAlign: "center",
  },
});
